FROM dpaws/microtrader-base
MAINTAINER Justin Menga <justin.menga@gmail.com>
LABEL application.component=quote-generator

# Copy application artefacts
ARG app_version
LABEL application.version=${app_version}
COPY build/jars/quote-generator-${app_version}-fat.jar /app/app.jar